### ISSUE TITLE
git stash save is deprecated

### ISSUE THREAD

**Issue by xtendo-org** [simnalamburt/cgitc#45]
[`git stash save` is deprecated in favour of `git stash push`](https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-save-p--patch-k--no-keep-index-u--include-untracked-a--all-q--quietltmessagegt). Currently `gsta` is `git stash save`, and there is no abbreviation for `git stash push`.

**Comment by simnalamburt** [comment]
Acknowledged. I'm considering reverting `gsta` back to `git stash` instead of `git stash save` or `git stash push`

**Comment by simnalamburt** [comment]
Closed by https://github.com/simnalamburt/cgitc/commit/6a21fe078a38c78f8ed3b431c3d752aab4f19e8f
